version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gozon_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gozon_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d gozon_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gozon_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: gozon_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - gozon_net

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: order-service
    container_name: order_service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - ./services/order-service:/app/src_mount
    networks:
      - gozon_net

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: payment-service
    container_name: payment_service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8080"
    networks:
      - gozon_net

  frontend:
    build: ./frontend
    container_name: gozon_frontend
    ports:
      - "3000:80"
    networks:
      - gozon_net

volumes:
  postgres_data:

networks:
  gozon_net:
    driver: bridge